### ISSUE TITLE
Cannot figure out how to create one tensorflow session and keep it open

### ISSUE THREAD

**Issue by rioffe** [rioffe/CarND-Capstone-Solution#14]
Current code will keep creating tensorflow devices due to the following line:

with tf.Session() as sess: 

in light_classification/tl_detector.py

I tried to create 
self.sess = tf.Session(graph=self.detection_graph)

and then in run_inference_for_single_image

        with self.detection_graph.as_default():
            with self.sess.as_default() as sess:

But I get the following error:

[ERROR] [1522017712.254920]: bad callback: <bound method TLDetector.image_cb of <__main__.TLDetector object at 0x7f3c039355d0>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/rioffe/self_driving_car_class/CarND-Capstone-Solution/ros/src/tl_detector/tl_detector.py", line 99, in image_cb
    closest_tl_xy, light_wp, state = self.process_traffic_lights()
  File "/home/rioffe/self_driving_car_class/CarND-Capstone-Solution/ros/src/tl_detector/tl_detector.py", line 193, in process_traffic_lights
    state = self.get_light_state(self.lights[np.argmin(ds)])
  File "/home/rioffe/self_driving_car_class/CarND-Capstone-Solution/ros/src/tl_detector/tl_detector.py", line 159, in get_light_state
    return self.light_classifier.get_classification(image)
  File "/home/rioffe/self_driving_car_class/CarND-Capstone-Solution/ros/src/tl_detector/light_classification/tl_classifier.py", line 30, in get_classification
    output_dict = self.detector.run_inference_for_single_image(image)
  File "/home/rioffe/self_driving_car_class/CarND-Capstone-Solution/ros/src/tl_detector/light_classification/tl_detector.py", line 43, in run_inference_for_single_image
    feed_dict={image_tensor: np.expand_dims(image, 0)})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
InternalError: Blas SGEMM launch failed : m=65536, n=64, k=24
	 [[Node: FeatureExtractor/InceptionV2/InceptionV2/Conv2d_1a_7x7/separable_conv2d = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](FeatureExtractor/InceptionV2/InceptionV2/Conv2d_1a_7x7/separable_conv2d/depthwise, FeatureExtractor/InceptionV2/Conv2d_1a_7x7/pointwise_weights)]]
	 [[Node: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/strided_slice_1/_75 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1158_...ed_slice_1", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopPostprocessor/BatchMultiClassNonMaxSuppression/map/while/strided_slice/stack_1/_11)]]

Caused by op u'FeatureExtractor/InceptionV2/InceptionV2/Conv2d_1a_7x7/separable_conv2d', defined at:
  File "/home/rioffe/self_driving_car_class/CarND-Capstone-Solution/ros/src/tl_detector/tl_detector.py", line 200, in <module>
    TLDetector()
  File "/home/rioffe/self_driving_car_class/CarND-Capstone-Solution/ros/src/tl_detector/tl_detector.py", line 54, in __init__
    self.light_classifier = TLClassifier()
  File "/home/rioffe/self_driving_car_class/CarND-Capstone-Solution/ros/src/tl_detector/light_classification/tl_classifier.py", line 11, in __init__
    self.detector = TLDetector(model_path)
  File "/home/rioffe/self_driving_car_class/CarND-Capstone-Solution/ros/src/tl_detector/light_classification/tl_detector.py", line 18, in __init__
    tf.import_graph_def(od_graph_def, name='')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 553, in import_graph_def
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InternalError (see above for traceback): Blas SGEMM launch failed : m=65536, n=64, k=24
	 [[Node: FeatureExtractor/InceptionV2/InceptionV2/Conv2d_1a_7x7/separable_conv2d = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](FeatureExtractor/InceptionV2/InceptionV2/Conv2d_1a_7x7/separable_conv2d/depthwise, FeatureExtractor/InceptionV2/Conv2d_1a_7x7/pointwise_weights)]]
	 [[Node: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/strided_slice_1/_75 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1158_...ed_slice_1", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopPostprocessor/BatchMultiClassNonMaxSuppression/map/while/strided_slice/stack_1/_11)]]

**Comment by rioffe** [comment]
class TLDetector(object):
    def __init__(self, model_path):
        path_to_ckpt = model_path + '/frozen_inference_graph.pb'
        self.detection_graph = tf.Graph()
        with self.detection_graph.as_default():
            od_graph_def = tf.GraphDef()
            with tf.gfile.GFile(path_to_ckpt, 'rb') as fid:
                serialized_graph = fid.read()
                od_graph_def.ParseFromString(serialized_graph)
                tf.import_graph_def(od_graph_def, name='')
                #self.graph_init_op = tf.global_variables_initializer()
        
        self.sess = tf.Session(graph=self.detection_graph)
        #self.sess.run(self.graph_init_op)

    def run_inference_for_single_image(self, image):
        with self.detection_graph.as_default():
            with self.sess.as_default() as sess:
                # Get handles to input and output tensors
                ops = tf.get_default_graph().get_operations()
                all_tensor_names = {output.name for op in ops for output in op.outputs}
                tensor_dict = {}
                for key in [
                    'num_detections', 'detection_boxes', 'detection_scores', 'detection_classes'
                ]:
                    tensor_name = key + ':0'
                    if tensor_name in all_tensor_names:
                        tensor_dict[key] = tf.get_default_graph().get_tensor_by_name(
                            tensor_name)

                image_tensor = tf.get_default_graph().get_tensor_by_name('image_tensor:0')

                # Run inference
                output_dict = sess.run(tensor_dict,
                                       feed_dict={image_tensor: np.expand_dims(image, 0)})

                # all outputs are float32 numpy arrays, so convert types as appropriate
                output_dict['num_detections'] = int(output_dict['num_detections'][0])
                output_dict['detection_classes'] = output_dict['detection_classes'][0].astype(np.uint8)
                output_dict['detection_boxes'] = output_dict['detection_boxes'][0]
                output_dict['detection_scores'] = output_dict['detection_scores'][0]
        return output_dict

**Comment by rioffe** [comment]
I think I solved the session issue with the latest commit on the branch, but still need to test it on a real system, since I am back home.
