### ISSUE TITLE
When running tensorflow under ROS, I get CUBLAS_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by rioffe** [rioffe/CarND-Capstone-Solution#16]
So far wasn't able to resolve the issue.

```
[INFO] [1522158065.805556]: image_cb is called
2018-03-27 06:41:07.228565: E tensorflow/stream_executor/cuda/cuda_blas.cc:444] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2018-03-27 06:41:07.228591: W tensorflow/stream_executor/stream.cc:1901] attempting to perform BLAS operation using StreamExecutor without BLAS support
[ERROR] [1522158067.230025]: bad callback: <bound method TLDetector.image_cb of <__main__.TLDetector object at 0x7f9838e5cdd0>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/rioffe/self_driving_car_class/CarND-Capstone-Solution/ros/src/tl_detector/tl_detector.py", line 99, in image_cb
    closest_tl_xy, light_wp, state = self.process_traffic_lights()
  File "/home/rioffe/self_driving_car_class/CarND-Capstone-Solution/ros/src/tl_detector/tl_detector.py", line 193, in process_traffic_lights
    state = self.get_light_state(self.lights[np.argmin(ds)])
  File "/home/rioffe/self_driving_car_class/CarND-Capstone-Solution/ros/src/tl_detector/tl_detector.py", line 159, in get_light_state
    return self.light_classifier.get_classification(image)
  File "/home/rioffe/self_driving_car_class/CarND-Capstone-Solution/ros/src/tl_detector/light_classification/tl_classifier.py", line 30, in get_classification
    output_dict = self.detector.run_inference_for_single_image(image)
  File "/home/rioffe/self_driving_car_class/CarND-Capstone-Solution/ros/src/tl_detector/light_classification/tl_detector.py", line 46, in run_inference_for_single_image
    feed_dict={self.image_tensor: np.expand_dims(image, 0)})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
InternalError: Blas SGEMM launch failed : m=65536, n=64, k=24
	 [[Node: FeatureExtractor/InceptionV2/InceptionV2/Conv2d_1a_7x7/separable_conv2d = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](FeatureExtractor/InceptionV2/InceptionV2/Conv2d_1a_7x7/separable_conv2d/depthwise, FeatureExtractor/InceptionV2/Conv2d_1a_7x7/pointwise_weights)]]
	 [[Node: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/LoopCond/_155 = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2072_Postprocessor/BatchMultiClassNonMaxSuppression/map/while/LoopCond", tensor_type=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopPostprocessor/BatchMultiClassNonMaxSuppression/map/while/strided_slice/stack_1/_11)]]

Caused by op u'FeatureExtractor/InceptionV2/InceptionV2/Conv2d_1a_7x7/separable_conv2d', defined at:
  File "/home/rioffe/self_driving_car_class/CarND-Capstone-Solution/ros/src/tl_detector/tl_detector.py", line 200, in <module>
    TLDetector()
  File "/home/rioffe/self_driving_car_class/CarND-Capstone-Solution/ros/src/tl_detector/tl_detector.py", line 54, in __init__
    self.light_classifier = TLClassifier()
  File "/home/rioffe/self_driving_car_class/CarND-Capstone-Solution/ros/src/tl_detector/light_classification/tl_classifier.py", line 11, in __init__
    self.detector = TLDetector(model_path)
  File "/home/rioffe/self_driving_car_class/CarND-Capstone-Solution/ros/src/tl_detector/light_classification/tl_detector.py", line 22, in __init__
    tf.import_graph_def(od_graph_def, name='')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 316, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 554, in import_graph_def
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InternalError (see above for traceback): Blas SGEMM launch failed : m=65536, n=64, k=24
	 [[Node: FeatureExtractor/InceptionV2/InceptionV2/Conv2d_1a_7x7/separable_conv2d = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](FeatureExtractor/InceptionV2/InceptionV2/Conv2d_1a_7x7/separable_conv2d/depthwise, FeatureExtractor/InceptionV2/Conv2d_1a_7x7/pointwise_weights)]]
	 [[Node: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/LoopCond/_155 = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2072_Postprocessor/BatchMultiClassNonMaxSuppression/map/while/LoopCond", tensor_type=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopPostprocessor/BatchMultiClassNonMaxSuppression/map/while/strided_slice/stack_1/_11)]]


[INFO] [1522158067.232028]: image_cb is called
2018-03-27 06:41:07.233066: I tensorflow/stream_executor/stream.cc:1851] stream 0x180d8f80 did not wait for stream: 0xada3ef0
2018-03-27 06:41:07.233089: I tensorflow/stream_executor/stream.cc:4637] stream 0x180d8f80 did not memcpy host-to-device; source: 0x7f9805a00000
2018-03-27 06:41:07.233127: F tensorflow/core/common_runtime/gpu/gpu_util.cc:343] CPU->GPU Memcpy failed
[tl_detector-8] process has died [pid 28553, exit code -6, cmd /home/rioffe/self_driving_car_class/CarND-Capstone-Solution/ros/src/tl_detector/tl_detector.py __name:=tl_detector __log:=/home/rioffe/.ros/log/7314028c-31c4-11e8-962e-1c1b0d675a18/tl_detector-8.log].
log file: /home/rioffe/.ros/log/7314028c-31c4-11e8-962e-1c1b0d675a18/tl_detector-8*.log
```

**Comment by rioffe** [comment]
Solved on the branch. Going to merge it to the mainline.
